services:
  prometheus:
    image: ubuntu/prometheus:2.53.3-24.04_stable
    restart: always
    container_name: prometheus-poc
    networks:
      - monitoring-observability-poc-network
    environment:
      TZ: UTC-3
    volumes:
      - ${PWD}/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - 9090:9090
    platform: linux/amd64
  grafana:
    image: grafana/grafana:11.4.0-ubuntu
    container_name: grafana-poc
    restart: always
    networks:
      - monitoring-observability-poc-network
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - 3000:3000
    platform: linux/amd64
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: capi
    restart: always
    networks:
      - monitoring-observability-poc-network
    environment:
        ASPNETCORE_ENVIRONMENT: Development
    ports:
      - 8080:8080
      - 1234:1234
    platform: linux/amd64
volumes:
  grafana-storage:
  prometheus-data:
networks:
  monitoring-observability-poc-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"